# Generated by Django 5.1 on 2024-10-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listings_category_alter_listings_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='active',
        ),
        migrations.RemoveField(
            model_name='listings',
            name='owner',
        ),
        migrations.AlterField(
            model_name='category',
            name='CategoryName',
            field=models.CharField(max_length=64),
        ),
    ]
