# Generated by Django 5.1 on 2024-11-05 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listings_active_listings_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='watchList',
            field=models.ManyToManyField(blank=True, null=True, related_name='watchList', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listings',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ownerListing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.FloatField(default=0)),
                ('user', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='userBid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='listings',
            name='price',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='priceListing', to='auctions.bid'),
        ),
    ]
