# Generated by Django 5.1 on 2024-11-05 15:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listings_watchlist_alter_listings_owner_bid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='watchList',
            field=models.ManyToManyField(blank=True, related_name='watchList', to=settings.AUTH_USER_MODEL),
        ),
    ]
