# Generated by Django 5.1 on 2024-11-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_listings_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='price',
            field=models.FloatField(),
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
    ]
